version: '3.7'

# Dev docker-compose
# Assumes a .env file assigning all env varibles
services:
  web:
    build: .
    # wait for db; see https://docs.docker.com/compose/startup-order/
    command: ["wait-for-it", "db:${POSTGRES_PORT}", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    # substitue command below to use Gunicorn instead of dev server
    # command: ["wait-for-it", "db:${POSTGRES_PORT}", "--", "gunicorn", "djxj_project.wsgi", "--reload", "-b", "0.0.0.0:8000"]
    environment:
      - PRODUCTION=False
      - SECRET_KEY=${SECRET_KEY}
      - EXTERNAL_HOST_NAME=${EXTERNAL_HOST_NAME}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_USER}

    volumes:
      - .:/home/appuser/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_USER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
