version: '3.7'

services:
  web:
    build: .
    # wait for db; see https://docs.docker.com/compose/startup-order/
    command: ["wait-for-it", "db:5432", "--", "gunicorn", "djxj_project.wsgi", "-b", "0.0.0.0:8000"]
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=True
      - PRODUCTION=False
      - EXTERNAL_HOST_NAME=$EXTERNAL_HOST_NAME
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_NAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

    volumes:
      - .:/home/appuser/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_NAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
